default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost

  username: postgres
  password: password
  pool: 5


development:
  <<: *default
  database: time_management_app
  username: postgres
  password: password

test:
  <<: *default
  database: time_management_app_test

production:
  <<: *default
  database: rails_app_production
  username: rails_app
  password: <%= ENV["RAILS_APP_DATABASE_PASSWORD"] %>_management_production
  pool: 5
  username: rubyuser      # Ensure this is the correct username
  password: password # Ensure this is the correct password
  host: <%= ENV['DATABASE_HOST'] %>